title: Gitify - GitHub Notifications on your menu bar
description: > # Site Description
  GitHub Notifications on your menu bar.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.gitify.io" # the base hostname & protocol for your site

# Build settings
exclude: ['.gitignore', 'node_modules', 'package.json']
